"""One-shot script to generate realistic seed data for the pipeline cache."""
import json, hashlib
from datetime import datetime, timedelta, timezone

now = datetime.now(timezone.utc)
def ago(d): return (now - timedelta(days=d)).isoformat()
def sid(cid, url, st):
    h = hashlib.sha1(f"{url}|{st}".encode()).hexdigest()[:10]
    return f"sg_{cid}_{h}"
def mk(cid, st, stren, hl, rat, sn, sr, url, da):
    return {"id":sid(cid,url,st),"type":st,"strength":stren,"headline":hl,"rationale":rat,"detected_at":ago(da),"source":{"title":hl,"url":url,"source_name":sn,"source_region":sr,"published_at":ago(da),"summary":None}}

cos = [
{"id":"co_mubadala_c6f8cb","name":"Mubadala Capital","aliases":["Mubadala"],"description":"Abu Dhabi sovereign wealth fund managing over USD 300B in assets globally.","sectors":["fintech","artificial_intelligence","energy"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[],"website":None,"founded_year":2002,"employee_band":None,"last_funding_usd":900000000,"total_funding_usd":900000000,"investability_score":95,"uae_alignment_score":98,"signals":[mk("co_mubadala_c6f8cb","partnership","high","Mubadala partners with G42 on AI infrastructure expansion","Joint initiative to deploy sovereign AI compute infrastructure across four Gulf states.","Arabian Business","GCC","https://arabianbusiness.com/mubadala-g42",2)],"first_seen":ago(14),"last_seen":ago(2)},
{"id":"co_ihc_5699ea","name":"IHC","aliases":["International Holding Company"],"description":"Abu Dhabi conglomerate, one of the most valuable listed companies in MENA.","sectors":["healthcare","real_estate","other"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[{"country":"Turkey","country_code":"TR","city":"Istanbul","lat":41.008,"lng":28.978}],"website":None,"founded_year":1998,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":90,"uae_alignment_score":96,"signals":[mk("co_ihc_5699ea","m_and_a","high","IHC completes USD 1.1B acquisition of Turkish healthcare group","Largest UAE-Turkey healthcare M&A of 2026.","Khaleej Times","UAE","https://khaleejtimes.com/ihc-turkey",3),mk("co_ihc_5699ea","expansion","high","IHC opens Istanbul office for Eurasia investments","Eurasia investment coordination hub.","Google News","UAE","https://news.google.com/ihc-istanbul",8)],"first_seen":ago(30),"last_seen":ago(3)},
{"id":"co_bain-capital_9111dc","name":"Bain Capital","aliases":[],"description":"Global PE firm with USD 180B AUM opening Abu Dhabi office.","sectors":["other","fintech"],"headquarters":{"country":"United States","country_code":"US","city":"New York","lat":40.7128,"lng":-74.006},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773}],"website":None,"founded_year":1984,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":82,"uae_alignment_score":92,"signals":[mk("co_bain-capital_9111dc","expansion","high","Bain Capital opens Abu Dhabi office for MENA deals","Signals commitment to regional capital deployment.","Google News","UAE","https://news.google.com/bain-abudhabi",1),mk("co_bain-capital_9111dc","expansion","high","Bain Capital deepens Middle East commitment","New Abu Dhabi hub for LP engagement.","Arabian Business","GCC","https://arabianbusiness.com/bain-me",2)],"first_seen":ago(5),"last_seen":ago(1)},
{"id":"co_tabby_a1b2c3","name":"Tabby","aliases":[],"description":"UAE BNPL fintech with 10M+ active shoppers across MENA.","sectors":["fintech","ecommerce"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},"expansion_targets":[{"country":"Saudi Arabia","country_code":"SA","city":"Riyadh","lat":24.7136,"lng":46.6753}],"website":None,"founded_year":2019,"employee_band":None,"last_funding_usd":200000000,"total_funding_usd":950000000,"investability_score":88,"uae_alignment_score":94,"signals":[mk("co_tabby_a1b2c3","funding","high","Tabby raises USD 200M Series D at USD 3.5B valuation","Led by Wellington Management, one of most valuable MENA fintech unicorns.","Wamda","MENA","https://wamda.com/tabby-series-d",5)],"first_seen":ago(30),"last_seen":ago(5)},
{"id":"co_g42_d4e5f6","name":"G42","aliases":["Group 42"],"description":"Abu Dhabi AI and cloud computing company building sovereign AI infrastructure.","sectors":["artificial_intelligence","healthcare"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[{"country":"United States","country_code":"US","city":"San Francisco","lat":37.7749,"lng":-122.4194}],"website":None,"founded_year":2018,"employee_band":None,"last_funding_usd":1500000000,"total_funding_usd":1500000000,"investability_score":92,"uae_alignment_score":97,"signals":[mk("co_g42_d4e5f6","partnership","high","G42 and Microsoft expand sovereign cloud to five markets","Abu Dhabi anchor hub for Azure sovereign infrastructure.","TechCrunch","Global","https://techcrunch.com/g42-msft",4),mk("co_g42_d4e5f6","funding","high","G42 secures USD 1.5B from Microsoft","Largest AI investment in the Middle East.","Crunchbase News","Global","https://news.crunchbase.com/g42-msft",20)],"first_seen":ago(60),"last_seen":ago(4)},
{"id":"co_stripe_g7h8i9","name":"Stripe","aliases":[],"description":"Global payments infrastructure processing hundreds of billions annually.","sectors":["fintech"],"headquarters":{"country":"United States","country_code":"US","city":"San Francisco","lat":37.7749,"lng":-122.4194},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2010,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":85,"uae_alignment_score":88,"signals":[mk("co_stripe_g7h8i9","expansion","high","Stripe secures DIFC license, opens Dubai office","Regulatory approval for MENA payments expansion.","Khaleej Times","UAE","https://khaleejtimes.com/stripe-difc",7)],"first_seen":ago(10),"last_seen":ago(7)},
{"id":"co_presight_j1k2l3","name":"Presight AI","aliases":[],"description":"Abu Dhabi big data analytics and AI company listed on ADX.","sectors":["artificial_intelligence","defense"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[],"website":None,"founded_year":2020,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":80,"uae_alignment_score":95,"signals":[mk("co_presight_j1k2l3","partnership","high","Presight wins USD 500M government analytics contract","Multi-year national security and urban planning deal.","Arabian Business","GCC","https://arabianbusiness.com/presight",6)],"first_seen":ago(20),"last_seen":ago(6)},
{"id":"co_masdar_m4n5o6","name":"Masdar","aliases":["Abu Dhabi Future Energy"],"description":"Abu Dhabi renewable energy company targeting 100 GW capacity by 2030.","sectors":["cleantech","energy"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[{"country":"Egypt","country_code":"EG","city":"Cairo","lat":30.0444,"lng":31.2357}],"website":None,"founded_year":2006,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":88,"uae_alignment_score":99,"signals":[mk("co_masdar_m4n5o6","expansion","high","Masdar breaks ground on 2 GW solar farm in Egypt","Construction begins on massive Aswan solar project.","Economy Middle East","MENA","https://economymiddleeast.com/masdar-egypt",9)],"first_seen":ago(45),"last_seen":ago(9)},
{"id":"co_revolut_p7q8r9","name":"Revolut","aliases":[],"description":"UK digital banking platform with 40M+ customers globally.","sectors":["fintech"],"headquarters":{"country":"United Kingdom","country_code":"GB","city":"London","lat":51.5074,"lng":-0.1278},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2015,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":82,"uae_alignment_score":85,"signals":[mk("co_revolut_p7q8r9","regulatory","high","Revolut receives DIFC Innovation License","Piloting digital banking in UAE market.","Khaleej Times","UAE","https://khaleejtimes.com/revolut-difc",11)],"first_seen":ago(14),"last_seen":ago(11)},
{"id":"co_rain_s1t2u3","name":"Rain","aliases":["Rain Financial"],"description":"Bahrain/UAE crypto exchange licensed by CBB and VARA.","sectors":["fintech"],"headquarters":{"country":"Bahrain","country_code":"BH","city":"Manama","lat":26.2285,"lng":50.586},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2017,"employee_band":None,"last_funding_usd":110000000,"total_funding_usd":110000000,"investability_score":75,"uae_alignment_score":90,"signals":[mk("co_rain_s1t2u3","regulatory","high","Rain obtains full VARA license for Dubai crypto trading","First exchanges with full VASP license from VARA.","MENAbytes","MENA","https://menabytes.com/rain-vara",14)],"first_seen":ago(20),"last_seen":ago(14)},
{"id":"co_adnoc_y7z8a9","name":"ADNOC","aliases":["Abu Dhabi National Oil Company"],"description":"Leading global energy company driving UAE energy transition.","sectors":["energy","manufacturing","cleantech"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[],"website":None,"founded_year":1971,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":90,"uae_alignment_score":99,"signals":[mk("co_adnoc_y7z8a9","partnership","high","ADNOC signs USD 6.2B LNG expansion deal","International consortium to expand Ruwais LNG capacity.","Arabian Business","GCC","https://arabianbusiness.com/adnoc-lng",3)],"first_seen":ago(40),"last_seen":ago(3)},
{"id":"co_databricks_b1c2d3","name":"Databricks","aliases":[],"description":"US data and AI platform valued at USD 60B+.","sectors":["artificial_intelligence"],"headquarters":{"country":"United States","country_code":"US","city":"San Francisco","lat":37.7749,"lng":-122.4194},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2013,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":80,"uae_alignment_score":82,"signals":[mk("co_databricks_b1c2d3","expansion","medium","Databricks opens Dubai MENA HQ","Regional headquarters in Dubai Internet City.","TechCrunch","Global","https://techcrunch.com/databricks-dubai",13)],"first_seen":ago(16),"last_seen":ago(13)},
{"id":"co_careem_h7i8j9","name":"Careem","aliases":[],"description":"Dubai super app for ride-hailing, delivery and fintech across 10+ markets.","sectors":["logistics","fintech","ecommerce"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},"expansion_targets":[{"country":"Pakistan","country_code":"PK","city":"Karachi","lat":24.8607,"lng":67.0011}],"website":None,"founded_year":2012,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":78,"uae_alignment_score":90,"signals":[mk("co_careem_h7i8j9","launch","high","Careem launches digital wallet and P2P payments in Pakistan","Extending fintech super app across the region.","Wamda","MENA","https://wamda.com/careem-wallet",8)],"first_seen":ago(20),"last_seen":ago(8)},
{"id":"co_lucid_k1l2m3","name":"Lucid Motors","aliases":[],"description":"US luxury EV maker with PIF-backed Saudi production facility.","sectors":["manufacturing","cleantech"],"headquarters":{"country":"United States","country_code":"US","city":"Newark","lat":37.5247,"lng":-122.0266},"expansion_targets":[{"country":"Saudi Arabia","country_code":"SA","city":"Jeddah","lat":21.4858,"lng":39.1925}],"website":None,"founded_year":2007,"employee_band":None,"last_funding_usd":1000000000,"total_funding_usd":6000000000,"investability_score":78,"uae_alignment_score":80,"signals":[mk("co_lucid_k1l2m3","expansion","high","Lucid begins production at KAEC plant in Saudi Arabia","First EV assembly plant in the GCC.","Google News","GCC","https://news.google.com/lucid-saudi",6)],"first_seen":ago(30),"last_seen":ago(6)},
{"id":"co_neom_c1d2e3","name":"NEOM","aliases":[],"description":"Saudi USD 500B mega-project for sustainable living and diversification.","sectors":["real_estate","cleantech","tourism","artificial_intelligence"],"headquarters":{"country":"Saudi Arabia","country_code":"SA","city":"NEOM","lat":28.0339,"lng":35.0934},"expansion_targets":[],"website":None,"founded_year":2017,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":85,"uae_alignment_score":70,"signals":[mk("co_neom_c1d2e3","partnership","high","NEOM signs AI partnerships for smart city infrastructure","AI deployment across The Line and Oxagon.","Google News","GCC","https://news.google.com/neom-ai",7)],"first_seen":ago(30),"last_seen":ago(7)},
{"id":"co_checkout_f4g5h6","name":"Checkout.com","aliases":[],"description":"UK payments company with DIFC HQ and strong MENA presence.","sectors":["fintech"],"headquarters":{"country":"United Kingdom","country_code":"GB","city":"London","lat":51.5074,"lng":-0.1278},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},{"country":"Saudi Arabia","country_code":"SA","city":"Riyadh","lat":24.7136,"lng":46.6753}],"website":None,"founded_year":2012,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":80,"uae_alignment_score":87,"signals":[mk("co_checkout_f4g5h6","expansion","high","Checkout.com integrates with STC Pay in Saudi","Extending payments infrastructure across the Kingdom.","Crunchbase News","Global","https://news.crunchbase.com/checkout-stc",9)],"first_seen":ago(15),"last_seen":ago(9)},
{"id":"co_pif_i7j8k9","name":"Public Investment Fund","aliases":["PIF"],"description":"Saudi sovereign wealth fund with USD 930B+ driving Vision 2030.","sectors":["other","artificial_intelligence","manufacturing"],"headquarters":{"country":"Saudi Arabia","country_code":"SA","city":"Riyadh","lat":24.7136,"lng":46.6753},"expansion_targets":[],"website":None,"founded_year":1971,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":92,"uae_alignment_score":75,"signals":[mk("co_pif_i7j8k9","m_and_a","high","PIF commits USD 40B to AI and semiconductor ventures","Vision 2030 diversification into deep tech.","Google News","GCC","https://news.google.com/pif-ai",2)],"first_seen":ago(20),"last_seen":ago(2)},
{"id":"co_dpworld_l1m2n3","name":"DP World","aliases":[],"description":"Dubai global logistics operator managing 78 terminals across 6 continents.","sectors":["logistics"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},"expansion_targets":[],"website":None,"founded_year":2005,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":85,"uae_alignment_score":97,"signals":[mk("co_dpworld_l1m2n3","expansion","high","DP World opens new Jebel Ali mega-terminal","Adding 5M TEU annual capacity.","Arabian Business","GCC","https://arabianbusiness.com/dpworld-jebelali",4)],"first_seen":ago(20),"last_seen":ago(4)},
{"id":"co_kitopi_v4w5x6","name":"Kitopi","aliases":[],"description":"Dubai cloud kitchen platform operating across the GCC.","sectors":["ecommerce","logistics"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},"expansion_targets":[{"country":"Saudi Arabia","country_code":"SA","city":"Riyadh","lat":24.7136,"lng":46.6753}],"website":None,"founded_year":2018,"employee_band":None,"last_funding_usd":60000000,"total_funding_usd":800000000,"investability_score":70,"uae_alignment_score":85,"signals":[mk("co_kitopi_v4w5x6","expansion","medium","Kitopi opens 15 new kitchens across Saudi Arabia","Riyadh, Jeddah and Dammam expansion.","Wamda","MENA","https://wamda.com/kitopi-saudi",10)],"first_seen":ago(25),"last_seen":ago(10)},
{"id":"co_invia_t1u2v3","name":"INVIA","aliases":[],"description":"Egyptian fintech building AI-powered financial OS for SMEs.","sectors":["fintech","artificial_intelligence"],"headquarters":{"country":"Egypt","country_code":"EG","city":"Cairo","lat":30.0444,"lng":31.2357},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2022,"employee_band":None,"last_funding_usd":1200000,"total_funding_usd":1200000,"investability_score":60,"uae_alignment_score":72,"signals":[mk("co_invia_t1u2v3","funding","high","INVIA raises USD 1.2M seed for SME financial OS","Targeting underserved Egyptian and MENA SMEs.","Wamda","MENA","https://wamda.com/invia-seed",5)],"first_seen":ago(10),"last_seen":ago(5)},
{"id":"co_sufra_z7a8b9","name":"Sufra AI","aliases":[],"description":"Qatar F&B tech startup using AI for menu optimization.","sectors":["artificial_intelligence","ecommerce"],"headquarters":{"country":"Qatar","country_code":"QA","city":"Doha","lat":25.2854,"lng":51.531},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2023,"employee_band":None,"last_funding_usd":100000,"total_funding_usd":100000,"investability_score":45,"uae_alignment_score":68,"signals":[mk("co_sufra_z7a8b9","funding","high","Sufra AI secures USD 100K pre-seed from Snoonu","Early-stage AI-driven F&B startup.","Wamda","MENA","https://wamda.com/sufra-ai",4)],"first_seen":ago(8),"last_seen":ago(4)},
{"id":"co_sarwa_n4o5p6","name":"Sarwa","aliases":[],"description":"Dubai robo-advisory platform regulated by DFSA.","sectors":["fintech"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},"expansion_targets":[],"website":None,"founded_year":2017,"employee_band":None,"last_funding_usd":15000000,"total_funding_usd":25000000,"investability_score":65,"uae_alignment_score":92,"signals":[mk("co_sarwa_n4o5p6","funding","medium","Sarwa raises USD 15M Series B","GCC expansion of wealth management platform.","MENAbytes","MENA","https://menabytes.com/sarwa-b",22)],"first_seen":ago(30),"last_seen":ago(22)},
{"id":"co_esa_e4f5g6","name":"Emirates Steel Arkan","aliases":["ESA"],"description":"UAE largest steel producer and industrial conglomerate.","sectors":["manufacturing","real_estate"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[],"website":None,"founded_year":1998,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":72,"uae_alignment_score":95,"signals":[mk("co_esa_e4f5g6","launch","medium","Emirates Steel begins green steel with hydrogen DRI","First in the Gulf to produce green steel.","Economy Middle East","MENA","https://economymiddleeast.com/esa-green",18)],"first_seen":ago(30),"last_seen":ago(18)},
{"id":"co_ceer_o4p5q6","name":"Ceer","aliases":["Ceer Motors"],"description":"Saudi first homegrown EV brand backed by PIF and Foxconn.","sectors":["manufacturing","cleantech"],"headquarters":{"country":"Saudi Arabia","country_code":"SA","city":"Riyadh","lat":24.7136,"lng":46.6753},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2022,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":72,"uae_alignment_score":78,"signals":[mk("co_ceer_o4p5q6","launch","high","Ceer unveils first production EV for GCC markets","Debut at Riyadh Motor Show targeting UAE launch.","Google News","GCC","https://news.google.com/ceer-ev",12)],"first_seen":ago(20),"last_seen":ago(12)},
{"id":"co_rakez_x4y5z6","name":"RAKEZ","aliases":[],"description":"Ras Al Khaimah free zone hosting 16000+ companies.","sectors":["real_estate","manufacturing"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Ras Al Khaimah","lat":25.6741,"lng":55.9804},"expansion_targets":[],"website":None,"founded_year":2017,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":68,"uae_alignment_score":95,"signals":[mk("co_rakez_x4y5z6","expansion","medium","RAKEZ reports 28% growth in new registrations Q1 2026","Manufacturing and logistics companies driving growth.","Khaleej Times","UAE","https://khaleejtimes.com/rakez-q1",8)],"first_seen":ago(15),"last_seen":ago(8)},
{"id":"co_anghami_q7r8s9","name":"Anghami","aliases":[],"description":"Abu Dhabi music streaming platform, first Arab tech company on NASDAQ.","sectors":["other","artificial_intelligence"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Abu Dhabi","lat":24.4539,"lng":54.3773},"expansion_targets":[],"website":None,"founded_year":2012,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":62,"uae_alignment_score":88,"signals":[mk("co_anghami_q7r8s9","launch","medium","Anghami launches AI Arabic music recommendation engine","First AI-native Arabic music recommendation in MENA.","Fast Company ME","MENA","https://fastcompanyme.com/anghami-ai",16)],"first_seen":ago(25),"last_seen":ago(16)},
{"id":"co_swvl_r7s8t9","name":"Swvl","aliases":[],"description":"Dubai mass transit tech company across MENA, Asia and LatAm.","sectors":["logistics"],"headquarters":{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708},"expansion_targets":[],"website":None,"founded_year":2017,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":55,"uae_alignment_score":80,"signals":[mk("co_swvl_r7s8t9","partnership","medium","Swvl partners with Dubai RTA on smart commuter routes","AI-optimized bus routes in underserved corridors.","Khaleej Times","UAE","https://khaleejtimes.com/swvl-rta",15)],"first_seen":ago(25),"last_seen":ago(15)},
{"id":"co_edafa_w4x5y6","name":"Edafa Venture","aliases":[],"description":"Egyptian venture builder in circular economy.","sectors":["cleantech","manufacturing"],"headquarters":{"country":"Egypt","country_code":"EG","city":"Cairo","lat":30.0444,"lng":31.2357},"expansion_targets":[],"website":None,"founded_year":2020,"employee_band":None,"last_funding_usd":None,"total_funding_usd":None,"investability_score":55,"uae_alignment_score":65,"signals":[mk("co_edafa_w4x5y6","m_and_a","medium","Edafa acquires waste recycling startup Cyclex","Active circular economy expansion in MENA.","Wamda","MENA","https://wamda.com/edafa-cyclex",5)],"first_seen":ago(10),"last_seen":ago(5)},
{"id":"co_saudi-emerge_u1v2w3","name":"Saudi Emerge","aliases":[],"description":"Riyadh B2B marketplace connecting GCC manufacturers globally.","sectors":["ecommerce","manufacturing"],"headquarters":{"country":"Saudi Arabia","country_code":"SA","city":"Riyadh","lat":24.7136,"lng":46.6753},"expansion_targets":[{"country":"United Arab Emirates","country_code":"AE","city":"Dubai","lat":25.2048,"lng":55.2708}],"website":None,"founded_year":2021,"employee_band":None,"last_funding_usd":8000000,"total_funding_usd":12000000,"investability_score":58,"uae_alignment_score":75,"signals":[mk("co_saudi-emerge_u1v2w3","partnership","medium","Saudi Emerge signs MoU with DMCC for UAE entry","Connecting GCC manufacturers with global trade.","MENAbytes","MENA","https://menabytes.com/saudi-emerge-dmcc",10)],"first_seen":ago(18),"last_seen":ago(10)},
]

snap = {"generated_at":now.isoformat(),"pipeline_run_ms":180000,"items":cos}
with open("cache/pipeline_snapshot.json","w") as f:
    json.dump(snap, f, default=str)
print(f"wrote {len(cos)} companies")
